### ISSUE TITLE
does the calendar need to be public?

### ISSUE THREAD

**Issue by lollilol** [acm-uic/calsync#48]
so after setting the project up for 4 hours i finally got it working:

```
syncing events
Request URL: https://content.googleapis.com/calendar/v3/calendars/***/events?singleEvents=true&timeMin=2024-09-26T20%3A30%3A30.986Z&timeMax=2024-10-10T20%3A30%3A30.986Z&maxResults=100&orderBy=startTime&key=***
Response status: 200
Received 0 calendar events.
```

This question should actually be answered by google docs, but i couldn't find anything about it. Everyone either says you should use a service account or oauth.
I only got it working by making the google calendar public. Is that the intended way? Because i can't find a way to give the api key permissions to my specific calendar.

**Comment by bmiddha** [comment]
Adding support for service accounts and private calendars in #50
